name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true  # Enable LFS checkout
          fetch-depth: 0  # Disable shallow clone
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Enforce your local Python 3.12.4
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs fetch --all
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          python -m spacy download en_core_web_sm
      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "mamidipaka2003@gmail.com"
          git config --global user.name "HarshaRockzz"
          git config --global lfs.allowincompletepush true  # Temporary fix
          export REMOTE_URL="https://HarshaRockzz:${HF_TOKEN}@huggingface.co/spaces/HarshaRockzz/Email-Classifier"
          git remote add space "$REMOTE_URL"
          git push --force space main
